"""
Reporter agent — Phase 3b & 5.
Generates fix prompts and the final report.md.
url is passed directly — never falls back to "Unknown".
"""

import asyncio
import json
import logging
import os
import re
from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Optional

from google import genai

logger = logging.getLogger("phantom")

MODEL = "gemini-2.0-flash"


def _make_client() -> genai.Client:
    return genai.Client(api_key=os.environ["GEMINI_API_KEY"])


class ReporterAgent:
    """Generates fix prompts and the final markdown report."""

    def __init__(self, reports_dir: Path = Path("reports")):
        self.reports_dir = Path(reports_dir)

    # ── Fix prompts ───────────────────────────────────────────────────────────

    async def generate_fix_prompts(self, bug_reports: list) -> list:
        """
        Generate one fix prompt file per bug report.
        Returns list of tuples: (relative_path, severity).
        """
        client = _make_client()
        generated_prompts = []

        fix_prompts_dir = self.reports_dir / "fix_prompts"
        fix_prompts_dir.mkdir(parents=True, exist_ok=True)

        for idx, report in enumerate(bug_reports, start=1):
            bug_id = f"{idx:03d}"
            title = report.get("title", "Unknown Bug")
            severity = report.get("severity", "low").upper()
            steps_list = report.get("steps_to_reproduce", [])
            steps = "\n".join(f"{i+1}. {s}" for i, s in enumerate(steps_list))
            expected = report.get("expected_behavior", "")
            actual = report.get("actual_behavior", "")
            affected_url = report.get("affected_url", "")
            screenshot_path = report.get("screenshot_path", "No screenshot available.")
            existing_fix = report.get("suggested_fix", "")

            prompt = f"""You are a senior developer writing a prompt that another AI coding agent will use to fix a bug.

Bug Report:
- Title: {title}
- Severity: {severity}
- Steps to reproduce:
{steps}
- Expected: {expected}
- Actual: {actual}
- Affected URL: {affected_url}
- Suggested Fix: {existing_fix}

Write a precise, copy-paste ready prompt (under 300 words) that:
1. Explains the bug clearly with full context
2. Lists the exact steps to reproduce
3. States what the correct behavior should be
4. Asks the AI to find the root cause and fix it specifically
5. Names the file type, function, or config that likely needs changing
6. Asks the AI to verify the fix doesn't break related functionality

Be specific and technical. Never write generic advice.
Return only the prompt text, nothing else."""

            generated_text = f"Fix the following bug:\n\nTitle: {title}\nSeverity: {severity}\nURL: {affected_url}\n\nSteps:\n{steps}\n\nExpected: {expected}\nActual: {actual}\n\nSuggested approach: {existing_fix}"

            for attempt in range(3):
                try:
                    logger.info(f"Gemini fix prompt (attempt {attempt+1}/3): {title[:50]}")
                    loop = asyncio.get_event_loop()
                    response = await loop.run_in_executor(
                        None,
                        lambda p=prompt: _make_client().models.generate_content(
                            model=MODEL, contents=p
                        ),
                    )
                    generated_text = response.text.strip()
                    break
                except Exception as e:
                    logger.warning(f"Fix prompt generation failed (attempt {attempt+1}): {e}")
                    if attempt < 2:
                        await asyncio.sleep(5)

            # Write the fix prompt file
            prompt_filename = fix_prompts_dir / f"fix_prompt_{bug_id}.md"
            md_lines = [
                "---",
                f"# Fix Prompt — {title}",
                f"Severity: {severity}",
                "Generated by Phantom QA Agent",
                "",
                "## Prompt (copy and paste this into your AI coding agent)",
                "",
                generated_text,
                "",
                "## Screenshot",
                str(screenshot_path),
                "---",
                "",
            ]
            prompt_filename.write_text("\n".join(md_lines), encoding="utf-8")

            generated_prompts.append((f"fix_prompts/fix_prompt_{bug_id}.md", severity))
            await asyncio.sleep(4)

        return generated_prompts

    # ── Report writer — url passed directly, no "Unknown" fallback ───────────

    def write_report(
        self,
        url: str,
        name: str,
        pages: list,
        bug_reports: list,
        fix_prompts: list,
        regression: dict,
        journeys: list,
        duration: float,
        scan_start: datetime,
    ) -> str:
        """
        Generate and save report.md.
        url is always the actual target URL — never "Unknown".
        """
        self.reports_dir.mkdir(parents=True, exist_ok=True)
        summary_path = self.reports_dir / "report.md"

        scan_date_fmt = scan_start.strftime("%Y-%m-%d %H:%M:%S UTC")
        duration_fmt = f"{duration:.0f}"

        total_bugs = len(bug_reports)
        visited_count = len(pages)
        journeys_count = len(journeys)
        coverage_pct = min(round((visited_count / max(8, 1)) * 100), 100)
        cov_str = f"{coverage_pct}%"

        severity_counter = Counter(r.get("severity", "low").lower() for r in bug_reports)

        def bar(sev):
            count = severity_counter.get(sev, 0)
            if total_bugs == 0:
                filled = 0
            else:
                filled = round((count / total_bugs) * 10)
            return ("█" * filled) + ("░" * (10 - filled))

        def pad_lines(text, pad="             "):
            if not text:
                return "None"
            if isinstance(text, list):
                if not text:
                    return "None"
                lines = [f"{i+1}. {s}" for i, s in enumerate(text)]
            else:
                lines = str(text).split("\n")
            if not lines:
                return "None"
            return lines[0] + "".join("\n" + pad + line for line in lines[1:])

        report = []
        report.append("================================================================================")
        report.append("██████╗ ██╗  ██╗ █████╗ ███╗   ██╗████████╗ ██████╗ ███╗   ███╗")
        report.append("██╔══██╗██║  ██║██╔══██╗████╗  ██║╚══██╔══╝██╔═══██╗████╗ ████║")
        report.append("██████╔╝███████║███████║██╔██╗ ██║   ██║   ██║   ██║██╔████╔██║")
        report.append("██╔═══╝ ██╔══██║██╔══██║██║╚██╗██║   ██║   ██║   ██║██║╚██╔╝██║")
        report.append("██║     ██║  ██║██║  ██║██║ ╚████║   ██║   ╚██████╔╝██║ ╚═╝ ██║")
        report.append("╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝   ╚═╝    ╚═════╝ ╚═╝     ╚═╝")
        report.append("")
        report.append("                   A U T O N O M O U S   Q A   A G E N T")
        report.append("================================================================================")
        report.append("")
        report.append(f"  Project   : {name}")
        report.append(f"  Target    : {url}")          # ← always real URL, never Unknown
        report.append(f"  Scan Date : {scan_date_fmt}")
        report.append(f"  Duration  : {duration_fmt}s")
        report.append("  Generated : Phantom QA Agent v2.0")
        report.append("")
        report.append("================================================================================")
        report.append("  SCAN SUMMARY")
        report.append("================================================================================")
        report.append("")
        report.append("  +-------------+----------+---------------+-----------+----------+")
        report.append("  | Bugs Found  | Journeys | Pages Visited | Coverage  | Duration |")
        report.append("  +-------------+----------+---------------+-----------+----------+")
        report.append(f"  | {total_bugs:^11} | {journeys_count:^8} | {visited_count:^13} | {cov_str:^9} | {duration_fmt+'s':^8} |")
        report.append("  +-------------+----------+---------------+-----------+----------+")
        report.append("")
        report.append("  Severity Breakdown")
        report.append("  ------------------")
        report.append(f"  CRITICAL  [{bar('critical')}]  {severity_counter.get('critical', 0)}")
        report.append(f"  HIGH      [{bar('high')}]  {severity_counter.get('high', 0)}")
        report.append(f"  MEDIUM    [{bar('medium')}]  {severity_counter.get('medium', 0)}")
        report.append(f"  LOW       [{bar('low')}]  {severity_counter.get('low', 0)}")
        report.append("")
        report.append("")
        report.append("================================================================================")
        report.append("  PAGES VISITED")
        report.append("================================================================================")
        report.append("")
        for i, page in enumerate(pages, 1):
            page_url = page.get("url", "") if isinstance(page, dict) else str(page)
            page_title = page.get("title", "") if isinstance(page, dict) else ""
            report.append(f"  {i:02d}. {page_url}")
            if page_title:
                report.append(f"       Title: {page_title}")
        report.append("")
        report.append("")
        report.append("================================================================================")
        report.append("  JOURNEYS EXECUTED")
        report.append("================================================================================")
        report.append("")
        if not journeys:
            report.append("  [*] No journeys executed.")
        else:
            for idx, j in enumerate(journeys, start=1):
                name = j.get("name", "Unknown Journey")
                status = "FAILED" if j.get("failed") else "PASSED"
                report.append(f"  #{idx:03d}  {name:<25} — {status}")
        report.append("")
        report.append("")
        report.append("================================================================================")
        report.append("  BUGS FOUND")
        report.append("================================================================================")
        report.append("")

        if not bug_reports:
            report.append("  [*] No bugs found during this scan.")
            report.append("")
        else:
            for idx, bug in enumerate(bug_reports, start=1):
                sev = bug.get("severity", "low").upper()
                cat = bug.get("category", "unknown")
                title = pad_lines(bug.get('title', 'Unknown'))
                report.append(f"  #{idx:03d}  {sev}  {title}")
                report.append("  -----------------------------------------------------------------------")
                urls = bug.get('affected_urls', [])
                if not urls:
                    urls = [bug.get('affected_url', url)]
                report.append(f"        Affected URLs: {len(urls)}")
                for u in urls:
                    report.append(f"        - {u}")
                report.append(f"  Steps    : {pad_lines(bug.get('steps_to_reproduce', []))}")
                report.append(f"  Expected : {pad_lines(bug.get('expected_behavior', ''))}")
                report.append(f"  Actual   : {pad_lines(bug.get('actual_behavior', ''))}")
                report.append(f"  Fix      : {pad_lines(bug.get('suggested_fix', ''))}")
                report.append("  -----------------------------------------------------------------------")
                report.append("")

        report.append("")
        report.append("================================================================================")
        report.append("  REGRESSION DELTA")
        report.append("================================================================================")
        report.append("")

        regressions = regression.get("regressions", []) if regression else []
        fixed = regression.get("fixed", []) if regression else []

        report.append("  Regressions (bugs that came back)")
        report.append("  ----------------------------------")
        if regressions:
            for r in regressions:
                report.append(f"  [!] {r}")
        else:
            report.append("  [*] No regressions detected")
        report.append("")

        report.append("  Fixed Since Last Scan")
        report.append("  ----------------------")
        if fixed:
            for f_ in fixed:
                report.append(f"  [+] {f_}")
        else:
            report.append("  [*] No verified fixes")
        report.append("")
        report.append("")

        report.append("================================================================================")
        report.append("  FIX PROMPTS")
        report.append("================================================================================")
        report.append("")
        if not fix_prompts:
            report.append("  [*] No fix prompts generated.")
        else:
            report.append("  Fix prompts generated for each bug.")
            report.append("  Paste into Cursor, Antigravity, or Claude to get an AI fix.")
            report.append("")
            for idx, (p_file, _) in enumerate(fix_prompts):
                title = bug_reports[idx].get("title", "Unknown") if idx < len(bug_reports) else "Unknown"
                report.append(f"  {p_file:<31} ->  {title}")

        report.append("")
        report.append("")
        report.append("================================================================================")
        report.append("  OUTPUT FILES")
        report.append("================================================================================")
        report.append("")
        report.append("  report.md      -> this file")
        report.append(f"  screenshots/   -> {total_bugs} screenshots at moment of each bug")
        report.append(f"  fix_prompts/   -> {len(fix_prompts)} ready-to-paste AI fix prompts")
        report.append("  phantom.log    -> full execution log")
        report.append("")
        report.append("")
        report.append("================================================================================")
        report.append("  END OF REPORT")
        report.append("  Phantom QA Agent v2.0")
        report.append("================================================================================")
        report.append("")

        markdown = "\n".join(report)
        summary_path.write_text(markdown, encoding="utf-8")
        logger.info(f"Report saved to {summary_path}")
        return markdown

    # ── Legacy alias — keep backward compatibility ────────────────────────────

    def generate_summary(
        self,
        project_name: str,
        bug_reports: list,
        app_model: dict,
        regression_delta: dict,
        fix_prompts: list,
        scan_start_time: datetime,
        scan_end_time: datetime,
    ) -> str:
        """Legacy wrapper — calls write_report() with app_model fields."""
        url = app_model.get("base_url") or app_model.get("url") or "Unknown"
        pages = app_model.get("crawled_urls", [])
        journeys = app_model.get("journeys", [])
        duration = (scan_end_time - scan_start_time).total_seconds()
        return self.write_report(
            url=url,
            name=project_name,
            pages=[{"url": u, "title": ""} for u in pages],
            bug_reports=bug_reports,
            fix_prompts=fix_prompts,
            regression=regression_delta,
            journeys=journeys,
            duration=duration,
            scan_start=scan_start_time,
        )
