"""
Reporter agent — Phase 3b.
Generates the final summary.md and regression delta report.
"""

import asyncio
import json
import logging
import os
import re
from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Optional

from google import genai

logger = logging.getLogger("phantom")

def _make_client() -> genai.Client:
    return genai.Client(api_key=os.environ["GEMINI_API_KEY"])

MODEL = "gemini-1.5-flash"

REPORTS_DIR = Path("reports")
SUMMARY_PATH = REPORTS_DIR / "summary.md"


class ReporterAgent:
    """Generates the final markdown summary report and fix prompts."""
    
    def __init__(self, reports_dir: Path = Path("reports")):
        self.reports_dir = reports_dir

    def _find_related_files(self, title: str) -> list[str]:
        words = re.findall(r'[a-zA-Z]{3,}', title.lower())
        noise = {'error', 'failed', 'issue', 'found', 'console', 'bug', 'the', 'and', 'with', 'for'}
        keywords = [w for w in words if w not in noise]
        
        if not keywords:
            return []

        root = Path(".")
        exclude_dirs = {"node_modules", ".git", "venv", "__pycache__", "reports", "memory", ".gemini"}
        
        matched_files = []
        for path in root.rglob("*"):
            if not path.is_file():
                continue
            if any(part in exclude_dirs for part in path.parts):
                continue
                
            path_str = str(path).lower()
            score = sum(1 for kw in keywords if kw in path_str)
            if score > 0:
                matched_files.append((score, str(path)))
                
        matched_files.sort(key=lambda x: x[0], reverse=True)
        return [f[1] for f in matched_files[:3]]

    async def generate_fix_prompts(self, bug_reports: list[dict], progress_callback=None) -> list[tuple[str, str]]:
        client = _make_client()
        generated_prompts = []
        
        for idx, report in enumerate(bug_reports, start=1):
            bug_id = f"{idx:03d}"
            
            title = report.get("title", "Unknown Bug")
            severity = report.get("severity", "low").upper()
            steps_list = report.get("steps_to_reproduce", [])
            steps = "\n".join(f"{i+1}. {s}" for i, s in enumerate(steps_list))
            expected = report.get("expected_behavior", "")
            actual = report.get("actual_behavior", "")
            affected_url = report.get("affected_url", "")
            screenshot_path = report.get("screenshot_path", "")
            if not screenshot_path:
                screenshot_path = "No screenshot available."

            if progress_callback:
                progress_callback(f"Generating fix prompt [{idx}/{len(bug_reports)}]: {title[:40]}")

            related_files = self._find_related_files(title)
            
            prompt = f"""You are a senior developer writing a prompt that another AI coding agent will use to fix a bug.

Bug Report:
- Title: {title}
- Severity: {severity}
- Steps to reproduce: {steps}
- Expected: {expected}
- Actual: {actual}
- Affected URL: {affected_url}

Write a precise, copy-paste ready prompt that:
1. Explains the bug clearly with full context
2. Lists the exact steps to reproduce
3. States what the correct behavior should be
4. Asks the AI to find the root cause and fix it
5. Asks the AI to make sure the fix doesn't break related functionality

Keep it under 300 words. Be specific, not generic. Return only the prompt text, nothing else."""

            generated_text = "Failed to generate prompt due to API error."
            for attempt in range(5):
                try:
                    logger.info(f"Gemini fix prompt (attempt {attempt+1}/5): {title[:50]}")
                    loop = asyncio.get_event_loop()
                    response = await loop.run_in_executor(
                        None,
                        lambda p=prompt: client.models.generate_content(
                            model=MODEL, contents=p
                        ),
                    )
                    
                    generated_text = response.text.strip()
                    break
                except Exception as e:
                    logger.warning(f"Generating fix prompt failed (attempt {attempt+1}): {e}")
                    if attempt < 4:
                        await asyncio.sleep(5)
            
            self.reports_dir.mkdir(parents=True, exist_ok=True)
            fix_prompts_dir = self.reports_dir / "fix_prompts"
            fix_prompts_dir.mkdir(parents=True, exist_ok=True)
            
            prompt_filename = fix_prompts_dir / f"fix_prompt_{bug_id}.md"
            
            md_lines = [
                "---",
                f"# Fix Prompt — {title}",
                f"Severity: {severity}",
                "Generated by Phantom QA Agent",
                "",
                "## Prompt (copy and paste this into your AI coding agent)",
                "",
                generated_text,
                ""
            ]
            
            if related_files:
                md_lines.append("## Related Files Found")
                for fpath in related_files:
                    md_lines.append(f"- `{fpath}`")
                md_lines.append("")
                
            md_lines.append("## Screenshot")
            md_lines.append(str(screenshot_path))
            md_lines.append("---")
            md_lines.append("")
            
            prompt_filename.write_text("\n".join(md_lines), encoding="utf-8")
            
            # Since fix prompts exist in a subdirectory relative to report.md,
            # we just append a relative string like 'fix_prompts/fix_prompt_001.md'
            # to make the output format exactly as the user specified.
            generated_prompts.append((f"fix_prompts/fix_prompt_{bug_id}.md", severity))
            
            await asyncio.sleep(4)
            
        return generated_prompts

    def generate_summary(
        self,
        project_name: str,
        bug_reports: list[dict],
        app_model: dict,
        regression_delta: dict,
        fix_prompts: list,
        scan_start_time: datetime,
        scan_end_time: datetime,
    ) -> str:
        """Generate and save report.md using pure ASCII formatting."""

        self.reports_dir.mkdir(parents=True, exist_ok=True)
        summary_path = self.reports_dir / "report.md"

        duration_sec = (scan_end_time - scan_start_time).total_seconds()
        duration_fmt = f"{duration_sec:.0f}"
        scan_date_fmt = scan_start_time.strftime("%Y-%m-%d %H:%M:%S UTC")
        
        journeys = app_model.get("journeys", [])
        crawled_urls = app_model.get("crawled_urls", [])
        graph_nodes = app_model.get("interaction_graph", {}).get("nodes", [])
        base_url = app_model.get("base_url", "Unknown")

        total_bugs = len(bug_reports)
        visited_count = len(crawled_urls)
        total_discovered = len(graph_nodes) if graph_nodes else visited_count
        coverage_pct = round((visited_count / total_discovered) * 100) if total_discovered > 0 else 0
        cov_str = f"{coverage_pct}%"

        # Count severities
        from collections import Counter
        severity_counter = Counter(r.get("severity", "low").lower() for r in bug_reports)
        
        def bar(sev):
            count = severity_counter.get(sev, 0)
            if total_bugs == 0:
                filled = 0
            else:
                filled = round((count / total_bugs) * 10)
            return ("█" * filled) + ("░" * (10 - filled))

        def pad_lines(text, pad="             "):
            if not text: return "None"
            if isinstance(text, list):
                if not text: return "None"
                lines = [f"{i+1}. {s}" for i, s in enumerate(text)]
            else:
                lines = str(text).split("\n")
            if not lines: return "None"
            return lines[0] + "".join("\n" + pad + line for line in lines[1:])

        report = []
        report.append("================================================================================")
        report.append("    ____  __  _____    _    _   _ _______ ____  __  __")
        report.append(r"   |  _ \|  || ___ \  / \  | \ | |__   __|  _ \|  \/  |")
        report.append(r"   | |_) | |_| |_/ / / _ \ |  \| |  | |  | |_) | |\/| |")
        report.append(r"   |  __/|  _|  _ < / ___ \| |\  |  | |  |  _ <| |  | |")
        report.append(r"   |_|   |_| |_| \_/_/   \_|_| \_|  |_|  |_| \_|_|  |_|")
        report.append("")
        report.append("                   A U T O N O M O U S   Q A   A G E N T")
        report.append("================================================================================")
        report.append("")
        report.append(f"  Project   : {project_name}")
        report.append(f"  Target    : {base_url}")
        report.append(f"  Scan Date : {scan_date_fmt}")
        report.append(f"  Duration  : {duration_fmt}s")
        report.append("  Generated : Phantom QA Agent v1.0")
        report.append("")
        report.append("================================================================================")
        report.append("  SCAN SUMMARY")
        report.append("================================================================================")
        report.append("")
        report.append("  +-------------+----------+---------------+-----------+----------+")
        report.append("  | Bugs Found  | Journeys | Pages Visited | Coverage  | Duration |")
        report.append("  +-------------+----------+---------------+-----------+----------+")
        report.append(f"  | {total_bugs:^11} | {len(journeys):^8} | {visited_count:^13} | {cov_str:^9} | {duration_fmt+'s':^8} |")
        report.append("  +-------------+----------+---------------+-----------+----------+")
        report.append("")
        report.append("  Severity Breakdown")
        report.append("  ------------------")
        report.append(f"  CRITICAL  [{bar('critical')}]  {severity_counter.get('critical', 0)}")
        report.append(f"  HIGH      [{bar('high')}]  {severity_counter.get('high', 0)}")
        report.append(f"  MEDIUM    [{bar('medium')}]  {severity_counter.get('medium', 0)}")
        report.append(f"  LOW       [{bar('low')}]  {severity_counter.get('low', 0)}")
        report.append("")
        report.append("")
        report.append("================================================================================")
        report.append("  BUGS FOUND")
        report.append("================================================================================")
        report.append("")
        
        if not bug_reports:
            report.append("  [*] No bugs found during this scan.")
            report.append("")
        else:
            for idx, bug in enumerate(bug_reports, start=1):
                sev = bug.get("severity", "low").upper()
                cat = bug.get("category", "unknown")
                # Title padding logic to handle multiline safely though title is usually 1 line
                report.append(f"  #{idx:03d}  {sev}  {cat}")
                report.append("  -----------------------------------------------------------------------")
                report.append(f"  Title    : {pad_lines(bug.get('title', 'Unknown'))}")
                report.append(f"  URL      : {pad_lines(bug.get('affected_url', ''))}")
                report.append(f"  Steps    : {pad_lines(bug.get('steps_to_reproduce', []))}")
                report.append(f"  Expected : {pad_lines(bug.get('expected_behavior', ''))}")
                report.append(f"  Actual   : {pad_lines(bug.get('actual_behavior', ''))}")
                report.append(f"  Fix      : {pad_lines(bug.get('suggested_fix', ''))}")
                report.append("  -----------------------------------------------------------------------")
                report.append("")

        report.append("")
        report.append("================================================================================")
        report.append("  REGRESSION DELTA")
        report.append("================================================================================")
        report.append("")
        
        regressions = regression_delta.get("regressions", [])
        fixed = regression_delta.get("fixed", [])
        
        report.append("  Regressions (bugs that came back)")
        report.append("  ----------------------------------")
        if regressions:
            for r in regressions:
                report.append(f"  [!] {r}")
        else:
            report.append("  [*] No regressions detected")
        report.append("")
        
        report.append("  Fixed Since Last Scan")
        report.append("  ----------------------")
        if fixed:
            for f_ in fixed:
                report.append(f"  [+] {f_}")
        else:
            report.append("  [*] No verified fixes")
        report.append("")
        report.append("")
        
        report.append("================================================================================")
        report.append("  FIX PROMPTS")
        report.append("================================================================================")
        report.append("")
        if not fix_prompts:
            report.append("  [*] No fix prompts generated.")
        else:
            report.append("  Fix prompts have been generated for each bug.")
            report.append("  Paste them into Cursor, Antigravity, or Claude")
            report.append("  to get an AI-assisted fix with full context.")
            report.append("")
            # fix_prompts contains list of tuples: (filename, severity)
            # we need to match it with titles inside bug_reports.
            # Usually they are 1:1 matching by index.
            for idx, (p_file, _) in enumerate(fix_prompts):
                title = bug_reports[idx].get("title", "Unknown") if idx < len(bug_reports) else "Unknown"
                report.append(f"  {p_file:<31} ->  {title}")
                
        report.append("")
        report.append("")
        report.append("================================================================================")
        report.append("  OUTPUT FILES")
        report.append("================================================================================")
        report.append("")
        report.append("  report.md      -> this file")
        report.append(f"  screenshots/   -> {total_bugs} screenshots at moment of each bug")
        report.append(f"  fix_prompts/   -> {len(fix_prompts)} ready-to-paste AI fix prompts")
        report.append("  phantom.log    -> full execution log")
        report.append("")
        report.append("")
        report.append("================================================================================")
        report.append("  END OF REPORT")
        report.append("  Phantom QA Agent | github.com/yourname/phantom-qa")
        report.append("================================================================================")
        report.append("")

        markdown = "\n".join(report)
        summary_path.write_text(markdown, encoding="utf-8")
        logger.info(f"Summary report saved to {summary_path}")
        return markdown
